export const MONGO_DATABASE_CONNECTION = 'MONGO_DATABASE_CONNECTION';
export const USER_MODEL = 'USER_MODEL';
export const PRODUCT_MODEL = 'PRODUCT_MODEL';
export const PRODUCT_REVIEW_MODEL = 'PRODUCT_REVIEW_MODEL';
